const createOptions = (values, labels) => values.map((value) => ({
  value,
  label: labels[value] || value,
}));

const createFormattedOptions = (values, formatLabel) => values.map((value) => ({
  value,
  label: formatLabel(value),
}));

const EXAM_LOADER_META_VALUES = new Set(["", "ALL APPLICABLE", "NOT APPLICABLE"]);
const removeExamLoaderMetaValues = (values) => values.filter((value) => !EXAM_LOADER_META_VALUES.has(value));

export const EXAM_CODE_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
];

export const EXAM_NAME_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
];

export const EXAM_LEVEL_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "INTERNATIONAL",
  "NATIONAL",
  "STATE",
  "REGIONAL",
  "UNIVERSITY",
  "INSTITUTIONAL",
  "OTHER",
];

export const EXAM_SECTOR_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "SSC_EXAMS': 'SSC Exams",
  "DEFENCE_EXAMS': 'Defence Exams",
  "UG_EXAMS': 'Undergraduate Exams",
  "PG_EXAMS': 'Postgraduate Exams",
  "BANKING_EXAMS': 'Banking Exams",
  "RAILWAY_EXAMS': 'Railway Exams",
  "TEACHING_EXAMS': 'Teaching Exams",
  "CIVIL_SERVICES_EXAMS': 'Civil Services",
  "POLICE_EXAMS': 'Police Exams",
  "ENGINEERING_RECRUITING_EXAMS': 'Engineering Recruitment",
  "INSURANCE_EXAMS': 'Insurance Exams",
  "JUDICIARY_ED': 'Judiciary Exams",
  "MBA_EXAMS': 'MBA Exams",
  "SCHOOL_EXAMS': 'School Level Exams",
  "NURSING_ED': 'Nursing Exams",
  "REGULATORY_BODY_ED': 'Regulatory Body Exams",
  "OTHER_GOV_ED': 'Other Government Exams",
  "OTHERS_ED': 'Other Exams",
  "CAMPUS_PLACEMENT_ED': 'Campus Placement",
  "ACCOUNTING_COMMERCE_ED': 'Accounting & Commerce",
];

export const EXAM_TARGET_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "OFFICER / GROUP A",
  "OFFICER / GROUP B",
  "CLERICAL / GROUP C",
  "GROUP D",
  "PROBATIONARY OFFICER",
  "MANAGEMENT TRAINEE",
  "ASSISTANT",
  "CLERK",
  "JUNIOR ENGINEER",
  "SENIOR ENGINEER",
  "TECHNICIAN",
  "CONSTABLE",
  "SUB INSPECTOR",
  "ASSISTANT COMMANDANT",
  "COMMANDANT",
  "LECTURER / PROFESSOR",
  "TEACHER",
  "MEDICAL OFFICER",
  "STAFF NURSE",
  "PHARMACIST",
  "CADET / TRAINEE",
  "SCIENTIST",
  "RESEARCHER",
  "JUDICIAL OFFICER",
  "ADVOCATE",
  "ADMISSION (UG)",
  "ADMISSION (PG)",
  "ADMISSION (PhD)",
  "FELLOWSHIP",
  "OTHER",
];

export const EXAM_FREQUENCY_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "1",
  "2",
  "3",
  "4",
  "IRREGULAR",
];

export const CONDUCTING_BODY_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
];

export const POSTS_CLASSES_COURSES_DEPARTMENTS_ACADEMIES_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
];

export const LATEST_UPDATED_DATE_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
];

export const EXAM_TIERS_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "SINGLE STAGE CBT",
  "TIER-I (PRELIMINARY)",
  "TIER-II (MAINS)",
  "TIER-III (DESCRIPTIVE)",
  "TIER-IV (SKILL TEST)",
  "PRELIMINARY EXAMINATION",
  "MAINS EXAMINATION",
  "INTERVIEW / PERSONALITY TEST",
  "PRELIMS + MAINS",
  "PRELIMS + MAINS + INTERVIEW",
  "CBT + PHYSICAL TEST",
  "CBT + SKILL TEST",
  "CBT + TYPING TEST",
  "WRITTEN + SSB INTERVIEW",
  "WRITTEN + SSB INTERVIEW + MEDICAL",
  "WRITTEN + PHYSICAL + MEDICAL",
  "ONLINE CBT",
  "OFFLINE (PEN AND PAPER)",
  "COMPUTER BASED TEST (CBT)",
  "DOCUMENT VERIFICATION",
  "MEDICAL EXAMINATION",
  "PHYSICAL EFFICIENCY TEST (PET)",
  "PHYSICAL STANDARD TEST (PST)",
  "TRADE TEST",
  "TECHNICAL TEST",
  "AFSB (Air Force Selection Board)",
  "SSB (Services Selection Board)",
  "OTHER",
];

export const EXAM_SUBJECTS_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "ENGLISH",
  "ENGLISH LANGUAGE",
  "ENGLISH LANGUAGE & COMPREHENSION",
  "HINDI",
  "GENERAL KNOWLEDGE",
  "GENERAL KNOWLEDGE / GENERAL AWARENESS",
  "GENERAL AWARENESS",
  "GENERAL AWARENESS / CURRENT AFFAIRS",
  "CURRENT AFFAIRS",
  "STATIC GK",
  "MATHEMATICS",
  "QUANTITATIVE APTITUDE",
  "NUMERICAL ABILITY",
  "QUANTITATIVE APTITUDE / MATHEMATICS",
  "REASONING",
  "LOGICAL REASONING",
  "ANALYTICAL REASONING",
  "GENERAL INTELLIGENCE",
  "GENERAL INTELLIGENCE & REASONING",
  "VERBAL REASONING",
  "NON-VERBAL REASONING",
  "DATA INTERPRETATION",
  "DATA ANALYSIS & INTERPRETATION",
  "COMPUTER KNOWLEDGE",
  "COMPUTER AWARENESS",
  "COMPUTER APTITUDE",
  "GENERAL SCIENCE",
  "PHYSICS",
  "CHEMISTRY",
  "BIOLOGY",
  "HISTORY",
  "GEOGRAPHY",
  "POLITY",
  "INDIAN POLITY",
  "ECONOMICS",
  "INDIAN ECONOMY",
  "ENVIRONMENT & ECOLOGY",
  "SCIENCE & TECHNOLOGY",
  "CSAT (CIVIL SERVICES APTITUDE TEST)",
  "ESSAY",
  "ETHICS, INTEGRITY & APTITUDE",
  "OPTIONAL SUBJECT",
  "TECHNICAL SUBJECT",
  "PROFESSIONAL KNOWLEDGE",
  "ENGINEERING SUBJECTS",
  "MEDICAL SUBJECTS",
  "LAW",
  "BANKING AWARENESS",
  "FINANCIAL AWARENESS",
  "INSURANCE AWARENESS",
  "RAILWAY AWARENESS",
  "AGRICULTURE",
  "PEDAGOGY",
  "CHILD DEVELOPMENT & PEDAGOGY",
  "TEACHING APTITUDE",
  "RESEARCH APTITUDE",
  "ENGLISH, GENERAL KNOWLEDGE",
  "ENGLISH, GENERAL KNOWLEDGE, MATHEMATICS",
  "ENGLISH, GENERAL INTELLIGENCE, QUANTITATIVE APTITUDE, GENERAL AWARENESS",
  "MCQ, MSQ, NAT",
  "AS PER SUBJECT",
  "COQP01 TO COQP22",
  "LAQP01 TO LAQP41",
  "SCQP01 TO SCQP30",
  "HUQP01 TO HUQP26",
  "MTQP01 TO MTQP12",
  "OTHER",
];

export const EXAM_PATTERN_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "OBJECTIVE TYPE",
  "OBJECTIVE TYPE (MCQ)",
  "OBJECTIVE TYPE (CBT)",
  "OBJECTIVE TYPE WRITTEN EXAM",
  "MULTIPLE CHOICE QUESTIONS (MCQ)",
  "MCQ",
  "MCQ, MSQ, NAT",
  "MCQ + DESCRIPTIVE",
  "DESCRIPTIVE TYPE",
  "ESSAY TYPE",
  "SUBJECTIVE",
  "MIXED (OBJECTIVE + DESCRIPTIVE)",
  "COMPUTER BASED TEST",
  "PEN AND PAPER",
  "ONLINE CBT",
  "OFFLINE PBT",
  "TYPING TEST",
  "SKILL TEST",
  "PRACTICAL TEST",
  "INTERVIEW",
  "PERSONALITY TEST",
  "PHYSICAL TEST",
  "AS PER TIER",
];

export const EXAM_SECTIONS_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "SECTION A",
  "SECTION B",
  "SECTION C",
  "SECTION A, B, C",
  "PART A, PART B",
  "PAPER I, PAPER II",
  "PAPER I, PAPER II, PAPER III",
  "ENGLISH, GK",
  "ENGLISH, GK, MATHS",
  "ENGLISH, MATHS, REASONING, GK",
  "GENERAL INTELLIGENCE, ENGLISH, QUANTITATIVE APTITUDE, GENERAL AWARENESS",
  "REASONING, ENGLISH, QUANTITATIVE, GENERAL AWARENESS",
  "REASONING, ENGLISH, QUANT, GA, COMPUTER",
  "GS, CSAT",
  "GS-I, GS-II, GS-III, GS-IV, OPTIONAL, ESSAY",
  "AS PER SUBJECT",
  "AS PER SYLLABUS",
];

export const MODE_OF_EXAM_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "ONLINE (COMPUTER BASED TEST)",
  "OFFLINE (PEN AND PAPER)",
  "OFFLINE (OMR BASED)",
  "ONLINE + OFFLINE",
  "CBT (COMPUTER BASED TEST)",
  "PBT (PEN BASED TEST)",
  "HYBRID",
  "REMOTE PROCTORED",
];

export const EXAM_DURATION_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "60 MINUTES",
  "60 MINUTES (TIER-1)",
  "90 MINUTES",
  "2 HOURS",
  "2 HOURS PER PAPER",
  "2.5 HOURS",
  "3 HOURS",
  "3 HOURS PER PAPER",
  "4 HOURS",
  "AS PER TIER",
  "AS PER PAPER",
  "VARIES BY SECTION",
];

export const TOTAL_MARKS_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "50",
  "100",
  "150",
  "200",
  "250",
  "300",
  "400",
  "500",
  "600",
  "700",
  "800",
  "1000",
  "1750",
  "2000",
  "2025",
  "AS PER TIER",
  "AS PER PAPER",
  "VARIES",
];

export const NUMBER_OF_QUESTIONS_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "25",
  "30",
  "40",
  "50",
  "60",
  "75",
  "100",
  "120",
  "150",
  "180",
  "200",
  "VARIES",
  "AS PER SECTION",
];

export const MARKING_SCHEME_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "NO NEGATIVE MARKING",
  "NEGATIVE MARKING",
  "NEGATIVE MARKING 1/4",
  "NEGATIVE MARKING 1/3",
  "NEGATIVE MARKING 0.25 MARKS",
  "NEGATIVE MARKING 0.50 MARKS",
  "NEGATIVE MARKING FOR MCQ",
  "NEGATIVE MARKING FOR WRONG ANSWERS",
  "DIFFERENTIAL MARKING",
  "1 MARK PER QUESTION",
  "2 MARKS PER QUESTION",
  "3 MARKS PER QUESTION",
  "4 MARKS PER QUESTION",
  "SECTION-WISE MARKING",
  "AS PER EXAM RULES",
];

export const PAPER_MEDIUM_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "ENGLISH",
  "HINDI",
  "ENGLISH, HINDI",
  "ENGLISH AND HINDI",
  "REGIONAL LANGUAGES",
  "SPECIFIC LANGUAGE",
  "BILINGUAL (ENGLISH/HINDI)",
  "ENGLISH, HINDI AND REGIONAL LANGUAGES",
  "TAMIL",
  "TELUGU",
  "KANNADA",
  "MALAYALAM",
  "MARATHI",
  "GUJARATI",
  "BENGALI",
  "PUNJABI",
  "ASSAMESE",
  "ODIA",
  "URDU",
  "KONKANI",
  "MANIPURI",
  "NEPALI",
  "SANSKRIT",
  "SINDHI",
  "KASHMIRI",
  "DOGRI",
  "BODO",
  "MAITHILI",
  "SANTHALI",
  "AS PER STATE",
  "AS PER EXAM RULES",
];

export const EXAM_FORM_LAST_DATE_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
];

export const AGE_CRITERIA_TYPE_VALUES_FOR_EXAM_LOADER = [
  "STARTING_AGE",
  "ENDING_AGE",
  "BETWEEN_AGE",
  "MINIMUM_DOB",
  "MAXIMUM_DOB",
  "BETWEEN_DOB",
  "NO_AGE_LIMIT",
];

export const EXAM_LEVEL_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_LEVEL_VALUES_FOR_EXAM_LOADER);
export const EXAM_SECTOR_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_SECTOR_VALUES_FOR_EXAM_LOADER);
export const EXAM_TARGET_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_TARGET_VALUES_FOR_EXAM_LOADER);
export const EXAM_FREQUENCY_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_FREQUENCY_VALUES_FOR_EXAM_LOADER);
export const EXAM_TIERS_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_TIERS_VALUES_FOR_EXAM_LOADER);
export const EXAM_SUBJECTS_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_SUBJECTS_VALUES_FOR_EXAM_LOADER);
export const EXAM_PATTERN_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_PATTERN_VALUES_FOR_EXAM_LOADER);
export const EXAM_SECTIONS_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_SECTIONS_VALUES_FOR_EXAM_LOADER);
export const MODE_OF_EXAM_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(MODE_OF_EXAM_VALUES_FOR_EXAM_LOADER);
export const EXAM_DURATION_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_DURATION_VALUES_FOR_EXAM_LOADER);
export const TOTAL_MARKS_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(TOTAL_MARKS_VALUES_FOR_EXAM_LOADER);
export const NUMBER_OF_QUESTIONS_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(NUMBER_OF_QUESTIONS_VALUES_FOR_EXAM_LOADER);
export const MARKING_SCHEME_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(MARKING_SCHEME_VALUES_FOR_EXAM_LOADER);
export const PAPER_MEDIUM_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(PAPER_MEDIUM_VALUES_FOR_EXAM_LOADER);

const GENDER_LABELS = {
  MALE: "Male",
  FEMALE: "Female",
  TRANSGENDER: "Transgender",
};

export const GENDER_VALUES = ["MALE", "FEMALE", "TRANSGENDER"];
export const GENDER_OPTIONS = createOptions(GENDER_VALUES, GENDER_LABELS);
export const GENDER_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  ...GENDER_VALUES,
];

export const CASTE_CATEGORY_LABELS = {
  GEN: "General (UR)",
  GENERAL: "General (UR/Unreserved)",
  "GENERAL (UR/UNRESERVED)": "General (UR/Unreserved)",
  OBC: "OBC",
  "OBC (OTHER BACKWARD CLASS)": "OBC (Other Backward Class)",
  EWS: "EWS",
  "EWS (ECONOMICALLY WEAKER SECTION)": "EWS (Economically Weaker Section)",
  SC: "SC",
  "SC (SCHEDULED CASTE)": "SC (Scheduled Caste)",
  ST: "ST",
  "ST (SCHEDULED TRIBE)": "ST (Scheduled Tribe)",
  MINORITY: "Minority",
};

export const CASTE_CATEGORY_VALUES = ["GEN", "OBC", "EWS", "SC", "ST"];
export const CASTE_CATEGORY_OPTIONS = createOptions(CASTE_CATEGORY_VALUES, CASTE_CATEGORY_LABELS);
export const CASTE_CATEGORY_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  ...CASTE_CATEGORY_VALUES,
];

const PWD_STATUS_LABELS = {
  YES: "Yes (PwD)",
  NO: "No",
};

export const PWD_STATUS_VALUES = ["YES", "NO"];
export const PWD_STATUS_OPTIONS = createOptions(PWD_STATUS_VALUES, PWD_STATUS_LABELS);
export const PWD_STATUS_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "APPLICABLE",
  ...PWD_STATUS_VALUES,
];
export const PWD_APPLICABILITY_OPTIONS = ["APPLICABLE", "NOT APPLICABLE"];

const NCC_WING_LABELS = {
  "ARMY WING": "Army Wing",
  "NAVAL WING": "Naval Wing",
  "AIR WING": "Air Wing",
};

export const NCC_WING_VALUES = ["ARMY WING", "NAVAL WING", "AIR WING"];
export const NCC_WING_OPTIONS = createOptions(NCC_WING_VALUES, NCC_WING_LABELS);
export const NCC_WING_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  ...NCC_WING_VALUES,
];

const NCC_CERTIFICATE_LABELS = {
  A: "A Cert",
  B: "B Cert",
  C: "C Cert",
};

export const NCC_CERTIFICATE_VALUES = ["A", "B", "C"];
export const NCC_CERTIFICATE_OPTIONS = createOptions(NCC_CERTIFICATE_VALUES, NCC_CERTIFICATE_LABELS);
export const NCC_CERTIFICATE_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  ...NCC_CERTIFICATE_VALUES,
];

const NCC_GRADE_LABELS = {
  A: "Grade A",
  B: "Grade B",
  C: "Grade C",
  D: "Grade D",
};

export const NCC_GRADE_VALUES = ["A", "B", "C", "D"];
export const NCC_GRADE_OPTIONS = createOptions(NCC_GRADE_VALUES, NCC_GRADE_LABELS);
export const NCC_GRADE_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  ...NCC_GRADE_VALUES,
];

const NATIONALITY_BASE_VALUES = [
  "INDIAN",
  "CITIZEN OF NEPAL",
  "CITIZEN OF BHUTAN",
  "TIBETAN REFUGEE (PRE-1962)",
  "PERSON OF INDIAN ORIGIN (PIO) FROM PAKISTAN",
  "PERSON OF INDIAN ORIGIN (PIO) FROM BURMA/MYANMAR",
  "PERSON OF INDIAN ORIGIN (PIO) FROM BANGLADESH",
  "PERSON OF INDIAN ORIGIN (PIO) FROM SRI LANKA",
  "PERSON OF INDIAN ORIGIN (PIO) FROM KENYA",
  "PERSON OF INDIAN ORIGIN (PIO) FROM UGANDA",
  "PERSON OF INDIAN ORIGIN (PIO) FROM TANZANIA",
  "PERSON OF INDIAN ORIGIN (PIO) FROM ZAMBIA",
  "PERSON OF INDIAN ORIGIN (PIO) FROM MALAWI",
  "PERSON OF INDIAN ORIGIN (PIO) FROM ZAIRE/DR CONGO",
  "PERSON OF INDIAN ORIGIN (PIO) FROM ETHIOPIA",
  "PERSON OF INDIAN ORIGIN (PIO) FROM SOUTH AFRICA",
  "PERSON OF INDIAN ORIGIN (PIO) FROM MAURITIUS",
  "PERSON OF INDIAN ORIGIN (PIO) FROM VIETNAM",
  "PERSON OF INDIAN ORIGIN (PIO) FROM MALAYSIA",
  "PERSON OF INDIAN ORIGIN (PIO) FROM SINGAPORE",
  "PERSON OF INDIAN ORIGIN (PIO) FROM INDONESIA",
  "PERSON OF INDIAN ORIGIN (PIO) FROM THAILAND",
  "PERSON OF INDIAN ORIGIN (PIO) FROM PHILIPPINES",
  "PERSON OF INDIAN ORIGIN (PIO) FROM OTHER COUNTRIES",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM UNITED STATES",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM UNITED KINGDOM",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM CANADA",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM AUSTRALIA",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM NEW ZEALAND",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM GERMANY",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM FRANCE",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM ITALY",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM NETHERLANDS",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM JAPAN",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM SOUTH KOREA",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM UAE",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM SAUDI ARABIA",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM QATAR",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM KUWAIT",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM OMAN",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM BAHRAIN",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM SOUTH AFRICA",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM MAURITIUS",
  "OCI (OVERSEAS CITIZEN OF INDIA) FROM OTHER COUNTRIES",
  "NRI (NON-RESIDENT INDIAN) IN UNITED STATES",
  "NRI (NON-RESIDENT INDIAN) IN UNITED KINGDOM",
  "NRI (NON-RESIDENT INDIAN) IN CANADA",
  "NRI (NON-RESIDENT INDIAN) IN AUSTRALIA",
  "NRI (NON-RESIDENT INDIAN) IN NEW ZEALAND",
  "NRI (NON-RESIDENT INDIAN) IN GERMANY",
  "NRI (NON-RESIDENT INDIAN) IN FRANCE",
  "NRI (NON-RESIDENT INDIAN) IN ITALY",
  "NRI (NON-RESIDENT INDIAN) IN NETHERLANDS",
  "NRI (NON-RESIDENT INDIAN) IN JAPAN",
  "NRI (NON-RESIDENT INDIAN) IN SINGAPORE",
  "NRI (NON-RESIDENT INDIAN) IN MALAYSIA",
  "NRI (NON-RESIDENT INDIAN) IN UAE",
  "NRI (NON-RESIDENT INDIAN) IN SAUDI ARABIA",
  "NRI (NON-RESIDENT INDIAN) IN QATAR",
  "NRI (NON-RESIDENT INDIAN) IN KUWAIT",
  "NRI (NON-RESIDENT INDIAN) IN OMAN",
  "NRI (NON-RESIDENT INDIAN) IN BAHRAIN",
  "NRI (NON-RESIDENT INDIAN) IN SOUTH AFRICA",
  "NRI (NON-RESIDENT INDIAN) IN MAURITIUS",
  "NRI (NON-RESIDENT INDIAN) IN OTHER COUNTRIES",
  "FOREIGN NATIONAL",
  "FOREIGN NATIONAL WITH INDIAN DEGREE",
  "FOREIGN NATIONAL WITH INDIAN ORIGIN",
];

const formatNationalityLabel = (value) => {
  if (!value) return "";

  const titleCased = value
    .toLowerCase()
    .replace(/\b[a-z]/g, (character) => character.toUpperCase());

  return titleCased
    .replace(/\bPio\b/g, "PIO")
    .replace(/\bOci\b/g, "OCI")
    .replace(/\bNri\b/g, "NRI")
    .replace(/\bDr\b/g, "DR")
    .replace(/\bUae\b/g, "UAE")
    .replace(/\bOf\b/g, "of")
    .replace(/\bFrom\b/g, "from")
    .replace(/\bIn\b/g, "in")
    .replace(/\bWith\b/g, "with")
    .replace(/\bAnd\b/g, "and");
};

export const NATIONALITY_VALUES = NATIONALITY_BASE_VALUES;
export const NATIONALITY_OPTIONS = createFormattedOptions(NATIONALITY_BASE_VALUES, formatNationalityLabel);
export const NATIONALITY_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  ...NATIONALITY_BASE_VALUES,
];

const DOMICILE_BASE_VALUES = [
  "ANDHRA PRADESH",
  "ARUNACHAL PRADESH",
  "ASSAM",
  "BIHAR",
  "CHHATTISGARH",
  "GOA",
  "GUJARAT",
  "HARYANA",
  "HIMACHAL PRADESH",
  "JHARKHAND",
  "KARNATAKA",
  "KERALA",
  "MADHYA PRADESH",
  "MAHARASHTRA",
  "MANIPUR",
  "MEGHALAYA",
  "MIZORAM",
  "NAGALAND",
  "ODISHA",
  "PUNJAB",
  "RAJASTHAN",
  "SIKKIM",
  "TAMIL NADU",
  "TELANGANA",
  "TRIPURA",
  "UTTAR PRADESH",
  "UTTARAKHAND",
  "WEST BENGAL",
  "ANDAMAN AND NICOBAR ISLANDS",
  "CHANDIGARH",
  "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
  "DELHI",
  "JAMMU AND KASHMIR",
  "LADAKH",
  "LAKSHADWEEP",
  "PUDUCHERRY",
];

export const DOMICILE_VALUES = DOMICILE_BASE_VALUES;
export const DOMICILE_OPTIONS = createFormattedOptions(DOMICILE_BASE_VALUES, formatNationalityLabel);
export const DOMICILE_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  ...DOMICILE_BASE_VALUES,
];

const MARITAL_STATUS_LABELS = {
  UNMARRIED: "Unmarried",
  MARRIED: "Married",
  SEPARATED: "Separated",
  DIVORCED: "Divorced",
  DIVORCEE: "Divorcee",
  WIDOW: "Widow",
  WIDOWER: "Widower",
};

export const MARITAL_STATUS_VALUES = [
  "UNMARRIED",
  "MARRIED",
  "SEPARATED",
  "DIVORCED",
  "DIVORCEE",
  "WIDOW",
  "WIDOWER",
];

export const MARITAL_STATUS_OPTIONS = createOptions(MARITAL_STATUS_VALUES, MARITAL_STATUS_LABELS);

const MARITAL_STATUS_VALUES_BY_GENDER = {
  MALE: ["UNMARRIED", "MARRIED", "SEPARATED", "DIVORCED", "WIDOWER"],
  FEMALE: ["UNMARRIED", "MARRIED", "SEPARATED", "DIVORCEE", "WIDOW"],
  TRANSGENDER: ["UNMARRIED", "MARRIED", "SEPARATED", "DIVORCED", "DIVORCEE", "WIDOWER", "WIDOW"],
};

const MARITAL_STATUS_VALUES_FOR_EXAM_LOADER_BY_GENDER = {
  MALE: [
    "",
    "ALL APPLICABLE",
    "NOT APPLICABLE",
    ...MARITAL_STATUS_VALUES_BY_GENDER.MALE,
  ],
  FEMALE: [
    "",
    "ALL APPLICABLE",
    "NOT APPLICABLE",
    ...MARITAL_STATUS_VALUES_BY_GENDER.FEMALE,
  ],
  TRANSGENDER: [
    "",
    "ALL APPLICABLE",
    "NOT APPLICABLE",
    ...MARITAL_STATUS_VALUES_BY_GENDER.TRANSGENDER,
  ],
};

export const MARITAL_STATUS_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  ...MARITAL_STATUS_VALUES,
];

const normalizeGender = (gender) => {
  if (!gender || typeof gender !== "string") return "";
  return gender.trim().toUpperCase();
};

export const getMaritalStatusValuesForGender = (gender) => {
  const normalizedGender = normalizeGender(gender);
  return MARITAL_STATUS_VALUES_FOR_EXAM_LOADER_BY_GENDER[normalizedGender] || MARITAL_STATUS_VALUES_FOR_EXAM_LOADER;
};

export const getMaritalStatusOptionsForGender = (gender) => {
  const normalizedGender = normalizeGender(gender);
  const values = MARITAL_STATUS_VALUES_BY_GENDER[normalizedGender] || MARITAL_STATUS_VALUES;
  return createOptions(values, MARITAL_STATUS_LABELS);
};
