const createOptions = (values, labels) => values.map((value) => ({
  value,
  label: labels[value] || value,
}));

const createFormattedOptions = (values, formatLabel) => values.map((value) => ({
  value,
  label: formatLabel(value),
}));

const EXAM_LOADER_META_VALUES = new Set(["", "ALL APPLICABLE", "NOT APPLICABLE"]);
const removeExamLoaderMetaValues = (values) => values.filter((value) => !EXAM_LOADER_META_VALUES.has(value));

export const EXAM_CODE_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
];

export const EXAM_NAME_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
];

export const EXAM_LEVEL_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "INTERNATIONAL",
  "NATIONAL",
  "STATE",
  "REGIONAL",
  "UNIVERSITY",
  "INSTITUTIONAL",
  "OTHER",
];

export const EXAM_SECTOR_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "SSC_EXAMS': 'SSC Exams",
  "DEFENCE_EXAMS': 'Defence Exams",
  "UG_EXAMS': 'Undergraduate Exams",
  "PG_EXAMS': 'Postgraduate Exams",
  "BANKING_EXAMS': 'Banking Exams",
  "RAILWAY_EXAMS': 'Railway Exams",
  "TEACHING_EXAMS': 'Teaching Exams",
  "CIVIL_SERVICES_EXAMS': 'Civil Services",
  "POLICE_EXAMS': 'Police Exams",
  "ENGINEERING_RECRUITING_EXAMS': 'Engineering Recruitment",
  "INSURANCE_EXAMS': 'Insurance Exams",
  "JUDICIARY_ED': 'Judiciary Exams",
  "MBA_EXAMS': 'MBA Exams",
  "SCHOOL_EXAMS': 'School Level Exams",
  "NURSING_ED': 'Nursing Exams",
  "REGULATORY_BODY_ED': 'Regulatory Body Exams",
  "OTHER_GOV_ED': 'Other Government Exams",
  "OTHERS_ED': 'Other Exams",
  "CAMPUS_PLACEMENT_ED': 'Campus Placement",
  "ACCOUNTING_COMMERCE_ED': 'Accounting & Commerce",
];

export const EXAM_TARGET_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "OFFICER / GROUP A",
  "OFFICER / GROUP B",
  "CLERICAL / GROUP C",
  "GROUP D",
  "PROBATIONARY OFFICER",
  "MANAGEMENT TRAINEE",
  "ASSISTANT",
  "CLERK",
  "JUNIOR ENGINEER",
  "SENIOR ENGINEER",
  "TECHNICIAN",
  "CONSTABLE",
  "SUB INSPECTOR",
  "ASSISTANT COMMANDANT",
  "COMMANDANT",
  "LECTURER / PROFESSOR",
  "TEACHER",
  "MEDICAL OFFICER",
  "STAFF NURSE",
  "PHARMACIST",
  "CADET / TRAINEE",
  "SCIENTIST",
  "RESEARCHER",
  "JUDICIAL OFFICER",
  "ADVOCATE",
  "ADMISSION (UG)",
  "ADMISSION (PG)",
  "ADMISSION (PhD)",
  "FELLOWSHIP",
  "OTHER",
];

export const EXAM_FREQUENCY_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "1",
  "2",
  "3",
  "4",
  "IRREGULAR",
];

export const CONDUCTING_BODY_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
];

export const POSTS_CLASSES_COURSES_DEPARTMENTS_ACADEMIES_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
];

export const LATEST_UPDATED_DATE_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
];

export const EXAM_TIERS_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "SINGLE STAGE CBT",
  "TIER-I (PRELIMINARY)",
  "TIER-II (MAINS)",
  "TIER-III (DESCRIPTIVE)",
  "TIER-IV (SKILL TEST)",
  "PRELIMINARY EXAMINATION",
  "MAINS EXAMINATION",
  "INTERVIEW / PERSONALITY TEST",
  "PRELIMS + MAINS",
  "PRELIMS + MAINS + INTERVIEW",
  "CBT + PHYSICAL TEST",
  "CBT + SKILL TEST",
  "CBT + TYPING TEST",
  "WRITTEN + SSB INTERVIEW",
  "WRITTEN + SSB INTERVIEW + MEDICAL",
  "WRITTEN + PHYSICAL + MEDICAL",
  "ONLINE CBT",
  "OFFLINE (PEN AND PAPER)",
  "COMPUTER BASED TEST (CBT)",
  "DOCUMENT VERIFICATION",
  "MEDICAL EXAMINATION",
  "PHYSICAL EFFICIENCY TEST (PET)",
  "PHYSICAL STANDARD TEST (PST)",
  "TRADE TEST",
  "TECHNICAL TEST",
  "AFSB (Air Force Selection Board)",
  "SSB (Services Selection Board)",
  "OTHER",
];

export const EXAM_SUBJECTS_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "ENGLISH",
  "ENGLISH LANGUAGE",
  "ENGLISH LANGUAGE & COMPREHENSION",
  "HINDI",
  "GENERAL KNOWLEDGE",
  "GENERAL KNOWLEDGE / GENERAL AWARENESS",
  "GENERAL AWARENESS",
  "GENERAL AWARENESS / CURRENT AFFAIRS",
  "CURRENT AFFAIRS",
  "STATIC GK",
  "MATHEMATICS",
  "QUANTITATIVE APTITUDE",
  "NUMERICAL ABILITY",
  "QUANTITATIVE APTITUDE / MATHEMATICS",
  "REASONING",
  "LOGICAL REASONING",
  "ANALYTICAL REASONING",
  "GENERAL INTELLIGENCE",
  "GENERAL INTELLIGENCE & REASONING",
  "VERBAL REASONING",
  "NON-VERBAL REASONING",
  "DATA INTERPRETATION",
  "DATA ANALYSIS & INTERPRETATION",
  "COMPUTER KNOWLEDGE",
  "COMPUTER AWARENESS",
  "COMPUTER APTITUDE",
  "GENERAL SCIENCE",
  "PHYSICS",
  "CHEMISTRY",
  "BIOLOGY",
  "HISTORY",
  "GEOGRAPHY",
  "POLITY",
  "INDIAN POLITY",
  "ECONOMICS",
  "INDIAN ECONOMY",
  "ENVIRONMENT & ECOLOGY",
  "SCIENCE & TECHNOLOGY",
  "CSAT (CIVIL SERVICES APTITUDE TEST)",
  "ESSAY",
  "ETHICS, INTEGRITY & APTITUDE",
  "OPTIONAL SUBJECT",
  "TECHNICAL SUBJECT",
  "PROFESSIONAL KNOWLEDGE",
  "ENGINEERING SUBJECTS",
  "MEDICAL SUBJECTS",
  "LAW",
  "BANKING AWARENESS",
  "FINANCIAL AWARENESS",
  "INSURANCE AWARENESS",
  "RAILWAY AWARENESS",
  "AGRICULTURE",
  "PEDAGOGY",
  "CHILD DEVELOPMENT & PEDAGOGY",
  "TEACHING APTITUDE",
  "RESEARCH APTITUDE",
  "ENGLISH, GENERAL KNOWLEDGE",
  "ENGLISH, GENERAL KNOWLEDGE, MATHEMATICS",
  "ENGLISH, GENERAL INTELLIGENCE, QUANTITATIVE APTITUDE, GENERAL AWARENESS",
  "MCQ, MSQ, NAT",
  "AS PER SUBJECT",
  "COQP01 TO COQP22",
  "LAQP01 TO LAQP41",
  "SCQP01 TO SCQP30",
  "HUQP01 TO HUQP26",
  "MTQP01 TO MTQP12",
  "OTHER",
];

export const EXAM_PATTERN_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "OBJECTIVE TYPE",
  "OBJECTIVE TYPE (MCQ)",
  "OBJECTIVE TYPE (CBT)",
  "OBJECTIVE TYPE WRITTEN EXAM",
  "MULTIPLE CHOICE QUESTIONS (MCQ)",
  "MCQ",
  "MCQ, MSQ, NAT",
  "MCQ + DESCRIPTIVE",
  "DESCRIPTIVE TYPE",
  "ESSAY TYPE",
  "SUBJECTIVE",
  "MIXED (OBJECTIVE + DESCRIPTIVE)",
  "COMPUTER BASED TEST",
  "PEN AND PAPER",
  "ONLINE CBT",
  "OFFLINE PBT",
  "TYPING TEST",
  "SKILL TEST",
  "PRACTICAL TEST",
  "INTERVIEW",
  "PERSONALITY TEST",
  "PHYSICAL TEST",
  "AS PER TIER",
];

export const EXAM_SECTIONS_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "SECTION A",
  "SECTION B",
  "SECTION C",
  "SECTION A, B, C",
  "PART A, PART B",
  "PAPER I, PAPER II",
  "PAPER I, PAPER II, PAPER III",
  "ENGLISH, GK",
  "ENGLISH, GK, MATHS",
  "ENGLISH, MATHS, REASONING, GK",
  "GENERAL INTELLIGENCE, ENGLISH, QUANTITATIVE APTITUDE, GENERAL AWARENESS",
  "REASONING, ENGLISH, QUANTITATIVE, GENERAL AWARENESS",
  "REASONING, ENGLISH, QUANT, GA, COMPUTER",
  "GS, CSAT",
  "GS-I, GS-II, GS-III, GS-IV, OPTIONAL, ESSAY",
  "AS PER SUBJECT",
  "AS PER SYLLABUS",
];

export const MODE_OF_EXAM_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "ONLINE (COMPUTER BASED TEST)",
  "OFFLINE (PEN AND PAPER)",
  "OFFLINE (OMR BASED)",
  "ONLINE + OFFLINE",
  "CBT (COMPUTER BASED TEST)",
  "PBT (PEN BASED TEST)",
  "HYBRID",
  "REMOTE PROCTORED",
];

export const EXAM_DURATION_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "60 MINUTES",
  "60 MINUTES (TIER-1)",
  "90 MINUTES",
  "2 HOURS",
  "2 HOURS PER PAPER",
  "2.5 HOURS",
  "3 HOURS",
  "3 HOURS PER PAPER",
  "4 HOURS",
  "AS PER TIER",
  "AS PER PAPER",
  "VARIES BY SECTION",
];

export const TOTAL_MARKS_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "50",
  "100",
  "150",
  "200",
  "250",
  "300",
  "400",
  "500",
  "600",
  "700",
  "800",
  "1000",
  "1750",
  "2000",
  "2025",
  "AS PER TIER",
  "AS PER PAPER",
  "VARIES",
];

export const NUMBER_OF_QUESTIONS_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "25",
  "30",
  "40",
  "50",
  "60",
  "75",
  "100",
  "120",
  "150",
  "180",
  "200",
  "VARIES",
  "AS PER SECTION",
];

export const MARKING_SCHEME_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "NO NEGATIVE MARKING",
  "NEGATIVE MARKING",
  "NEGATIVE MARKING 1/4",
  "NEGATIVE MARKING 1/3",
  "NEGATIVE MARKING 0.25 MARKS",
  "NEGATIVE MARKING 0.50 MARKS",
  "NEGATIVE MARKING FOR MCQ",
  "NEGATIVE MARKING FOR WRONG ANSWERS",
  "DIFFERENTIAL MARKING",
  "1 MARK PER QUESTION",
  "2 MARKS PER QUESTION",
  "3 MARKS PER QUESTION",
  "4 MARKS PER QUESTION",
  "SECTION-WISE MARKING",
  "AS PER EXAM RULES",
];

export const PAPER_MEDIUM_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "ENGLISH",
  "HINDI",
  "ENGLISH, HINDI",
  "ENGLISH AND HINDI",
  "REGIONAL LANGUAGES",
  "SPECIFIC LANGUAGE",
  "BILINGUAL (ENGLISH/HINDI)",
  "ENGLISH, HINDI AND REGIONAL LANGUAGES",
  "TAMIL",
  "TELUGU",
  "KANNADA",
  "MALAYALAM",
  "MARATHI",
  "GUJARATI",
  "BENGALI",
  "PUNJABI",
  "ASSAMESE",
  "ODIA",
  "URDU",
  "KONKANI",
  "MANIPURI",
  "NEPALI",
  "SANSKRIT",
  "SINDHI",
  "KASHMIRI",
  "DOGRI",
  "BODO",
  "MAITHILI",
  "SANTHALI",
  "AS PER STATE",
  "AS PER EXAM RULES",
];

export const EXAM_FORM_LAST_DATE_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
];

export const AGE_CRITERIA_TYPE_VALUES_FOR_EXAM_LOADER = [
  "STARTING_AGE",
  "ENDING_AGE",
  "BETWEEN_AGE",
  "MINIMUM_DOB",
  "MAXIMUM_DOB",
  "BETWEEN_DOB",
  "NO_AGE_LIMIT",
];

export const EXAM_LEVEL_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_LEVEL_VALUES_FOR_EXAM_LOADER);
export const EXAM_SECTOR_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_SECTOR_VALUES_FOR_EXAM_LOADER);
export const EXAM_TARGET_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_TARGET_VALUES_FOR_EXAM_LOADER);
export const EXAM_FREQUENCY_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_FREQUENCY_VALUES_FOR_EXAM_LOADER);
export const EXAM_TIERS_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_TIERS_VALUES_FOR_EXAM_LOADER);
export const EXAM_SUBJECTS_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_SUBJECTS_VALUES_FOR_EXAM_LOADER);
export const EXAM_PATTERN_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_PATTERN_VALUES_FOR_EXAM_LOADER);
export const EXAM_SECTIONS_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_SECTIONS_VALUES_FOR_EXAM_LOADER);
export const MODE_OF_EXAM_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(MODE_OF_EXAM_VALUES_FOR_EXAM_LOADER);
export const EXAM_DURATION_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(EXAM_DURATION_VALUES_FOR_EXAM_LOADER);
export const TOTAL_MARKS_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(TOTAL_MARKS_VALUES_FOR_EXAM_LOADER);
export const NUMBER_OF_QUESTIONS_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(NUMBER_OF_QUESTIONS_VALUES_FOR_EXAM_LOADER);
export const MARKING_SCHEME_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(MARKING_SCHEME_VALUES_FOR_EXAM_LOADER);
export const PAPER_MEDIUM_OPTIONS_FOR_EXAM_LOADER = removeExamLoaderMetaValues(PAPER_MEDIUM_VALUES_FOR_EXAM_LOADER);

const PWD_STATUS_LABELS = {
  YES: "Yes (PwD)",
  NO: "No",
};

export const PWD_STATUS_VALUES = ["YES", "NO"];
export const PWD_STATUS_OPTIONS = createOptions(PWD_STATUS_VALUES, PWD_STATUS_LABELS);
export const PWD_STATUS_VALUES_FOR_EXAM_LOADER = [
  "",
  "ALL APPLICABLE",
  "NOT APPLICABLE",
  "APPLICABLE",
  ...PWD_STATUS_VALUES,
];
export const PWD_APPLICABILITY_OPTIONS = ["APPLICABLE", "NOT APPLICABLE"];

